In [1]:
import pandas as pd
import numpy as np
import yaml

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [5]:
def clean_col_names(df):
    df2 = df.copy()
    df2.columns = df2.columns.map(lambda x: x.lower().replace(' ',''))
    return df2

def remove_empty_fields(df):
    df2 = df.copy()
    empty = df2[df2.iloc[:,-1]==9].index
    df2.iloc[empty,-2]= np.nan
    df2 = df2.interpolate()
    return df2

def remove_leap_days(df):
    df2 = df.copy()
    df2 = df2.sort_values('date', ascending=True)
    df2.date  = pd.to_datetime(df2.date, format='%Y%m%d')
    df_filtered = df2[df2['date'].dt.strftime('%m-%d') == '02-29']
    df2 = df2.drop(df_filtered.index.tolist())
    df2 = df2.reset_index(drop=True)
    return df2

def drop_columns(df):
    df2 = df.copy()
    if df2.columns[0]=='souid':
        df2 = df2.drop(columns = [df.columns[0]])
    if df2.columns[-1][0]=='q':
        df2 = df2.drop(columns = [df.columns[-1]])
    return df2

def filter_years(df):
    df2 = df.copy()
    df2['year']=df2.date.dt.year
    df2 = df2[df2.year >= 1991]
    return df2

def clean_data(df):
    df2= df.copy()
    df2 = clean_col_names(df2)
    df2 = remove_leap_days(df2)
    df2 = remove_empty_fields(df2)
    if sum(df2.iloc[:,-1]==1) == 0:
        df2 = drop_columns(df2)    
    else:
        print('has missing values')
    #df2 = filter_years(df2)
    return df2

In [6]:
df_cc = pd.read_csv(config['data']['raw']['file1'], quotechar='"', sep = ";")
df_cc = clean_data(df_cc)
df_cc.to_csv("../data/clean/cc.csv", index=False, encoding= "utf-8", sep = ";")

In [7]:
df_hu = pd.read_csv(config['data']['raw']['file2'], quotechar='"', sep = ";")
df_hu = clean_data(df_hu)

In [8]:
df_hu

            date    hu
0     1979-01-01  83.0
1     1979-01-02  76.0
2     1979-01-03  86.0
3     1979-01-04  68.0
4     1979-01-05  73.0
...          ...   ...
17150 2025-12-27  84.0
17151 2025-12-28  75.0
17152 2025-12-29  76.0
17153 2025-12-30  83.0
17154 2025-12-31  94.0

[17155 rows x 2 columns]

In [9]:
df_hu.to_csv("../data/clean/hu.csv", index=False, encoding= "utf-8", sep = ";")

In [10]:
df_pp = pd.read_csv(config['data']['raw']['file3'], quotechar='"', sep = ";")
df_pp = clean_data(df_pp)
df_pp

            date       pp
0     1979-01-01  10190.0
1     1979-01-02  10253.0
2     1979-01-03  10205.0
3     1979-01-04  10084.0
4     1979-01-05  10225.0
...          ...      ...
17150 2025-12-27  10341.0
17151 2025-12-28  10324.0
17152 2025-12-29  10293.0
17153 2025-12-30  10336.0
17154 2025-12-31  10291.0

[17155 rows x 2 columns]

In [11]:
df_pp.to_csv("../data/clean/pp.csv", index=False, encoding= "utf-8", sep = ";")

In [12]:
df_qq = pd.read_csv(config['data']['raw']['file4'], quotechar='"', sep = ";")
df_qq = clean_data(df_qq)
df_qq

            date    qq
0     1979-01-01  52.0
1     1979-01-02  27.0
2     1979-01-03  13.0
3     1979-01-04  13.0
4     1979-01-05  29.0
...          ...   ...
17150 2025-12-27  35.0
17151 2025-12-28  12.0
17152 2025-12-29  12.0
17153 2025-12-30  42.0
17154 2025-12-31  33.0

[17155 rows x 2 columns]

In [13]:
df_qq.to_csv("../data/clean/qq.csv", index=False, encoding= "utf-8", sep = ";")

In [14]:
df_rr = pd.read_csv(config['data']['raw']['file5'], quotechar='"', sep = ";")
df_rr = clean_data(df_rr)
df_rr

            date   rr
0     1979-01-01  4.0
1     1979-01-02  0.0
2     1979-01-03  0.0
3     1979-01-04  0.0
4     1979-01-05  0.0
...          ...  ...
17150 2025-12-27  0.0
17151 2025-12-28  0.0
17152 2025-12-29  0.0
17153 2025-12-30  0.0
17154 2025-12-31  0.0

[17155 rows x 2 columns]

In [15]:
df_rr.to_csv("../data/clean/rr.csv", index=False, encoding= "utf-8", sep = ";")

In [16]:
df_sd = pd.read_csv(config['data']['raw']['file6'], quotechar='"', sep = ";")
df_sd = clean_data(df_sd)
df_sd

            date   sd
0     1979-01-01  9.0
1     1979-01-02  8.0
2     1979-01-03  4.0
3     1979-01-04  2.0
4     1979-01-05  1.0
...          ...  ...
17150 2025-12-27  0.0
17151 2025-12-28  0.0
17152 2025-12-29  0.0
17153 2025-12-30  0.0
17154 2025-12-31  0.0

[17155 rows x 2 columns]

In [17]:
df_sd.to_csv("../data/clean/sd.csv", index=False, encoding= "utf-8", sep = ";")

In [18]:
df_ss = pd.read_csv(config['data']['raw']['file7'], quotechar='"', sep = ";")
df_ss = clean_data(df_ss)
df_ss

            date  ss
0     1979-01-01  70
1     1979-01-02  17
2     1979-01-03   0
3     1979-01-04   0
4     1979-01-05  20
...          ...  ..
17150 2025-12-27  33
17151 2025-12-28   0
17152 2025-12-29   0
17153 2025-12-30  47
17154 2025-12-31  29

[17155 rows x 2 columns]

In [19]:
df_ss.to_csv("../data/clean/ss.csv", index=False, encoding= "utf-8", sep = ";")

In [20]:
df_tg = pd.read_csv(config['data']['raw']['file8'], quotechar='"', sep = ";")
df_tg = clean_data(df_tg)
df_tg

has missing values

        souid       date  tg  q_tg
0      107054 1979-01-01 -41     0
1      107054 1979-01-02 -26     0
2      107054 1979-01-03 -28     0
3      107054 1979-01-04 -26     0
4      107054 1979-01-05  -8     0
...       ...        ...  ..   ...
17150  107054 2025-12-27  48     0
17151  107054 2025-12-28  54     0
17152  107054 2025-12-29  57     0
17153  107054 2025-12-30  48     1
17154  107054 2025-12-31   9     0

[17155 rows x 4 columns]

In [21]:
df_tn = pd.read_csv(config['data']['raw']['file9'], quotechar='"', sep = ";")
df_tn = clean_data(df_tn)
df_tn

            date  tn
0     1979-01-01 -75
1     1979-01-02 -75
2     1979-01-03 -72
3     1979-01-04 -65
4     1979-01-05 -14
...          ...  ..
17150 2025-12-27  19
17151 2025-12-28  35
17152 2025-12-29  47
17153 2025-12-30  23
17154 2025-12-31 -11

[17155 rows x 2 columns]

In [22]:
# df_tn.to_csv("../data/clean/tn.csv", index=False, encoding= "utf-8", sep = ";")

In [23]:
df_tx = pd.read_csv(config['data']['raw']['file10'], quotechar='"', sep = ";")
df_tx = clean_data(df_tx)
df_tx

            date  tx
0     1979-01-01  23
1     1979-01-02  16
2     1979-01-03  13
3     1979-01-04  -3
4     1979-01-05  56
...          ...  ..
17150 2025-12-27  73
17151 2025-12-28  66
17152 2025-12-29  73
17153 2025-12-30  29
17154 2025-12-31  61

[17155 rows x 2 columns]

In [24]:
# df_tx.to_csv("../data/clean/tx.csv", index=False, encoding= "utf-8", sep = ";")

In [25]:
df_tx, df_tn

(            date  tx
 0     1979-01-01  23
 1     1979-01-02  16
 2     1979-01-03  13
 3     1979-01-04  -3
 4     1979-01-05  56
 ...          ...  ..
 17150 2025-12-27  73
 17151 2025-12-28  66
 17152 2025-12-29  73
 17153 2025-12-30  29
 17154 2025-12-31  61

 [17155 rows x 2 columns],
             date  tn
 0     1979-01-01 -75
 1     1979-01-02 -75
 2     1979-01-03 -72
 3     1979-01-04 -65
 4     1979-01-05 -14
 ...          ...  ..
 17150 2025-12-27  19
 17151 2025-12-28  35
 17152 2025-12-29  47
 17153 2025-12-30  23
 17154 2025-12-31 -11

 [17155 rows x 2 columns])

In [26]:
df_tx.dtypes, df_tn.dtypes

(date    datetime64[us]
 tx               int64
 dtype: object,
 date    datetime64[us]
 tn               int64
 dtype: object)

In [27]:
a = df_tx.merge(df_tn, on='date')
#merge all temp values, as quality issues in q_tq relate to all three columns

In [28]:
b = a.merge(df_tg, on='date')
b

            date  tx  tn   souid  tg  q_tg
0     1979-01-01  23 -75  107054 -41     0
1     1979-01-02  16 -75  107054 -26     0
2     1979-01-03  13 -72  107054 -28     0
3     1979-01-04  -3 -65  107054 -26     0
4     1979-01-05  56 -14  107054  -8     0
...          ...  ..  ..     ...  ..   ...
17150 2025-12-27  73  19  107054  48     0
17151 2025-12-28  66  35  107054  54     0
17152 2025-12-29  73  47  107054  57     0
17153 2025-12-30  29  23  107054  48     1
17154 2025-12-31  61 -11  107054   9     0

[17155 rows x 6 columns]

In [29]:
b_err = b[b.q_tg==1]
#a 1 reflects suspect data

In [30]:
#first context for errors
c1 = b[(b.tx<b.tn) & (b.q_tg==1)]

In [31]:
#second context for errors
c2 = b[(b.tx==b.tn) & (b.q_tg==1)]

In [32]:
#third context
c3 = b[(b.tg>b.tx) & (b.q_tg==1)]

In [33]:
#how many values fall into these
c1.shape[0] + c2.shape[0] + c3.shape[0]

1461

In [34]:
#how many are there
b_err.shape[0]

1180

In [35]:
#which values are off
exclude_idx = np.concatenate([c1.index, c2.index, c3.index])

b_err_filtered = b_err[~b_err.index.isin(exclude_idx)]

In [36]:
#we plan to use data from 1991 onwards only, how many errors are in it
b_err[b_err['date'].dt.strftime('%y') >= '1991']

            date   tx  tn   souid   tg  q_tg
7     1979-01-08   58  53  107054   69     1
15    1979-01-16   26  41  107054   50     1
16    1979-01-17   19  16  107054   21     1
31    1979-02-01   40  12  107054   52     1
43    1979-02-13    2   3  107054   42     1
...          ...  ...  ..     ...  ...   ...
17122 2025-11-29   99  95  107054  106     1
17135 2025-12-12  106  90  107054  108     1
17145 2025-12-22   77  90  107054  102     1
17146 2025-12-23   63  72  107054   75     1
17153 2025-12-30   29  23  107054   48     1

[749 rows x 6 columns]

In [37]:
#how many are in the test split 
b_err[b_err['date'].dt.strftime('%y') > '2021']

            date   tx  tn   souid   tg  q_tg
7     1979-01-08   58  53  107054   69     1
15    1979-01-16   26  41  107054   50     1
16    1979-01-17   19  16  107054   21     1
31    1979-02-01   40  12  107054   52     1
43    1979-02-13    2   3  107054   42     1
...          ...  ...  ..     ...  ...   ...
17122 2025-11-29   99  95  107054  106     1
17135 2025-12-12  106  90  107054  108     1
17145 2025-12-22   77  90  107054  102     1
17146 2025-12-23   63  72  107054   75     1
17153 2025-12-30   29  23  107054   48     1

[722 rows x 6 columns]

In [38]:
b_err['year']= b_err.date.dt.year
#errors by year

In [39]:
all_y = b_err[(b_err.year >= 1991) & (b_err.year < 2021)]
#seeing how many errors in the training data

In [40]:
exclude_idx
#how many rows to remove

array([   15,    43,    44, ..., 17145, 17146, 17153], shape=(1461,))

In [41]:
df_tx.iloc[exclude_idx,1] = np.nan
df_tx = df_tx.interpolate()
df_tx.iloc[:,1] = df_tx.iloc[:,1]/10
#remove and interpolate over bad values
#also convert temp in 0.1 degrees to temp in degrees

In [42]:
df_tn.iloc[exclude_idx,1] = np.nan
df_tn = df_tn.interpolate()
df_tn.iloc[:,1] = df_tn.iloc[:,1]/10
#remove and interpolate over bad values
#also convert temp in 0.1 degrees to temp in degrees

In [43]:
df_tg = drop_columns(df_tg)
df_tg

            date  tg
0     1979-01-01 -41
1     1979-01-02 -26
2     1979-01-03 -28
3     1979-01-04 -26
4     1979-01-05  -8
...          ...  ..
17150 2025-12-27  48
17151 2025-12-28  54
17152 2025-12-29  57
17153 2025-12-30  48
17154 2025-12-31   9

[17155 rows x 2 columns]

In [44]:
df_tg.iloc[exclude_idx,1] = np.nan
df_tg = df_tg.interpolate()
df_tg.iloc[:,1] = df_tg.iloc[:,1]/10
#remove and interpolate over bad values
#also convert temp in 0.1 degrees to temp in degrees

In [45]:
df_tx.to_csv("../data/clean/tx.csv", index=False, encoding= "utf-8", sep = ";")
df_tn.to_csv("../data/clean/tn.csv", index=False, encoding= "utf-8", sep = ";")
df_tg.to_csv("../data/clean/tg.csv", index=False, encoding= "utf-8", sep = ";")

In [46]:
check1 = df_tx.merge(df_tn, on='date')
check2 = check1.merge(df_tg, on='date')
#want to check if it's solved

In [47]:
cont1 = check2[(check2.tx<check2.tn)]
cont2 = check2[(check2.tx==check2.tn) ]
cont3 = check2[(check2.tg>check2.tx)]
#how many errors in each context persist

In [48]:
cont1.shape[0] + cont2.shape[0] + cont3.shape[0]

0